/**
 * Player terms.
 *
 * IMPORTANT: a plain-language DRAFT, not reviewed by a lawyer. It exists so
 * players agree to something before walking somewhere, which they currently do
 * not — the single largest gap in docs/launch-readiness.md item 2. Creators
 * accept terms at publish; the person who can actually be injured accepts
 * nothing, and they are not party to the creator agreement.
 *
 * Three things deliberately NOT drafted here, because they are load-bearing and
 * inventing them would be worse than leaving them out:
 *   - governing law and venue
 *   - arbitration and any class-action waiver (evidently central to how
 *     Niantic's defence has held up; a real decision, not a default)
 *   - the precise liability cap and its carve-outs
 * Counsel should add those and rewrite anything below that needs it.
 *
 * PLAYER_TERMS_VERSION is recorded against each play in `player_sessions`.
 * Bump it whenever the substance changes so old acceptances aren't mistaken
 * for agreement to new wording. Use a date so records are self-describing.
 */

export const PLAYER_TERMS_VERSION = '2026-08-02';

export interface TermsSection {
  heading: string;
  body: string[];
}

export const PLAYER_TERMS_SECTIONS: TermsSection[] = [
  {
    heading: 'You are responsible for your own safety',
    body: [
      'These experiences take place outdoors, in real places, while you look at a phone. Traffic, kerbs, water, cliffs, weather, other people and uneven ground are all real, and none of them are managed by us.',
      'Watch where you are going. Stop walking before you look at the screen. Do not use this while driving, cycling, or operating anything.',
      'You take part at your own risk, and you are responsible for deciding whether a place and a moment are safe for you.',
    ],
  },
  {
    heading: 'We did not choose the locations',
    body: [
      'Every experience is made by an independent creator who chooses the coordinates. We do not visit them, inspect them, or verify that they are safe, legal to enter, or open to the public.',
      'A location appearing in an experience is not permission to be there. Respect private property, posted signs, opening hours, closures and local laws. If somewhere feels unsafe or unwelcome, leave.',
      'If an experience sends you somewhere it should not, please report it so we can remove it.',
    ],
  },
  {
    heading: 'The content comes from creators, not from us',
    body: [
      'Audio, images, characters and 3D objects are supplied by creators. Some conversations are generated by AI and can be wrong, invented, or out of character.',
      'Nothing in an experience is advice — not medical, legal, financial, navigational or emergency advice. Do not rely on it for anything that matters.',
      'In an emergency, call your local emergency number. This app is not a safety tool and cannot summon help.',
    ],
  },
  {
    heading: 'Location and data',
    body: [
      'The experience needs your location to work, and it is used on your device to decide when something should play. What we store is described in the privacy policy.',
      'You do not need an account to play, and we do not ask for your name.',
    ],
  },
  {
    heading: 'Younger players',
    body: [
      'If you are under 18, please take part with a parent or guardian, and only with their agreement.',
      'Some experiences contain mature themes chosen by their creator. Age suitability is not something we verify.',
    ],
  },
  {
    heading: 'What we do not promise',
    body: [
      'Experiences depend on GPS, your phone, your network and third-party services, all of which fail. Audio may not play, a location may not trigger, and an experience may be removed or changed by its creator at any time.',
      'We provide this as-is, without warranties, to the fullest extent the law allows.',
    ],
  },
  {
    heading: 'Reporting something',
    body: [
      'If an experience puts people at risk, sends them somewhere they should not go, or contains something that should not be there, report it from the player menu.',
      'We remove experiences that create a real-world hazard, and we do so without waiting to hear from the creator.',
    ],
  },
];
